[enron]
    name = "enron"
    src = "zenodo"
    href = "1eHoOsq9AgQLbAHDEpT8ZdyampgRku_Y3"

# [USLegis]
#     name = "USLegis"
#     src = "zenodo"
#     href = "https://zenodo.org/records/7213796/files/USLegis.zip"

# [UNtrade]
#     name = "UNtrade"
#     src = "zenodo"
#     href = "https://zenodo.org/records/7213796/files/UNtrade.zip"

# [DBLP]
#     name = "DBLP"
#     src = "gdrive"
#     href = ""

[tgbl-flight]
    name = "tgbl-flight"
    src = "tgb"
    href = "1eJ1LVd-IewkKc5PG-67vRCJlMKTvV9mI"

[tgbl-coin]
    name = "tgbl-coin"
    src = "tgb"
    href = "1jTvo1nHgIQKkptwqV141Ia92AGhlDpUX"