[eed]
    name = "eed"
    raw = "https://www.kaggle.com/datasets/tarun42/enron-clean/data"
    href = "1Kaeu8SKENMlUkT66qTltmgHirXeXwXIp"

[dblp]
    name = "dblp"
    raw = ""
    href = "1KYP3m6WVo9bb3igcGGZMLOdAokAt67jn"

[dblp_1936-2021]
    name = "dblp_1936-2021"
    raw = ""
    href = "1VGll5VrOIsXSaAzHryQExIpAuH-lk_uq"

[dblp_1936-2022]
    name = "dblp_1936-2022"
    raw = ""
    href = "1VG6ISzZsiUpTLDtSBJZnYRk9o9UHpDsp"

[dblp_1936-2023]
    name = "dblp_1936-2023"
    raw = ""
    href = "1VHyCUrIh1BQpZBUmZC8KgZNnq4XqO4QR"

[dblp_1936-2024]
    name = "dblp_1936-2024"
    raw = ""
    href = "1VJLUgi8_8wexTg4f_rZAaqzp-8ngVbTy"

[tgbl-flight]
    name = "tgbl-flight"
    raw = "TGB"
    href = "1eJ1LVd-IewkKc5PG-67vRCJlMKTvV9mI"

[tgbl-coin]
    name = "tgbl-coin"
    raw = "TGB"
    href = "1eKa9fD0OvG7cEgheeffy1J1xFFQIGQtN"