[eed]
    name = "eed"
    raw = "https://www.kaggle.com/datasets/tarun42/enron-clean/data"
    href = "1i1Ko1bK9HhV8QRIaDkTq3CTmKA6tbbVO"

[dblp]
    name = "dblp"
    raw = "https://www.kaggle.com/datasets/agungpambudi/research-citation-network-5m-papers?rvi=1"
    href = "1idEBmRa5w1BGxEfq1zqjUiQ3Nhc_RboX"

[tgbl-flight]
    name = "tgbl-flight"
    raw = "https://object-arbutus.cloud.computecanada.ca/tgb/tgbl-flight-v2.zip"
    href = "1ibtYQduhMoFDNORWC016TLKG44KxcWPB"

[GDELTLite]
    name = "GDELTLite"
    raw = "https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.datasets.GDELTLite.html?highlight=gde#torch_geometric.datasets.GDELTLite"
    href = "1i21pHHLaoyilvydO-VbIk0yXs5x4XR3Y"