[eed]
    name = "eed"
    raw = "https://www.kaggle.com/datasets/tarun42/enron-clean/data"
    href = "1Kaeu8SKENMlUkT66qTltmgHirXeXwXIp"

[dblp]
    name = "dblp"
    raw = ""
    href = "1KYP3m6WVo9bb3igcGGZMLOdAokAt67jn"

[tgbl-flight]
    name = "tgbl-flight"
    raw = "TGB"
    href = "1eJ1LVd-IewkKc5PG-67vRCJlMKTvV9mI"

[tgbl-coin]
    name = "tgbl-coin"
    raw = "TGB"
    href = "1eKa9fD0OvG7cEgheeffy1J1xFFQIGQtN"