[project]
name = "ntust-tg"
version = "0.1"
description = "Temporal Graph Datasets for PyTorch Geometric"
dependencies = [
    "torch>=2.8.0",
    "torch-geometric>=2.6.1",
    "gdown>=5.2.0",
    "tqdm>=4.67.1",
    "clint>=0.5.1",
    "requests>=2.32.4",
    "pandas>=2.3.1",
    "scikit-learn>=1.7.1",
    "toml>=0.10.2",
]
requires-python = ">=3.8"

[tool.poetry]
authors = ["Hsiang-Jen Li <hsiangjenli@gmail.com>"]
readme = "README.md"
packages = [{include = "temporal_graph"}]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 200

[tool.ruff.format]
docstring-code-line-length = 120
indent-style = "tab"
line-ending = "auto"
quote-style = "double"
skip-magic-trailing-comma = true
